window.modestoOptions = {
    CPNITries: "3",
    CPNIVerificationMethods: "['Last4CableCC', 'Last4MobileCC', 'CPNI Pin']",
    Test4: "50",
    activationPollingInterval: "30000",
    addChannelIdToActivation: true,
    addressConfigurableRetail: "false",
    addressConfigurableTelesales: "false",
    adobeDtmUrl: "https://assets.adobedtm.com/43896e740dcedef854392e0be6ea80deb8eb2ba5/satelliteLib-7ad87bc53da16dec2566b5621550331da97cf8c1-staging.js",
    agentsForLogger: "",
    allowDeactivation: false,
    allowWarrantyForAndroid: false,
    appleVoicemail: "https://help.apple.com/iphone/10/#/iph3c99490e",
    assurantTradeInPortalUrl: "https://websec-oic.cable.comcast.com/as/authorization.oauth2?scope=openid+profile&redirect_uri=http%3A%2F%2Fmodel-xm.st.assurantdevice.com%2Fqap%2Flogin%2FssotokenWebSec&response_type=code&client_id=xm-assurant-stg&pfidpadapterid=kerberos",
    attUnlock: "https://www.att.com/deviceunlock/#/",
    bypassVerification: "['Einstein Telesales', 'Einstein Global Admin']",
    canByodTelesales: false,
    canDoDeferred: "true",
    carrierUnlockUrl: "https://www.google.com/",
    claimsSubmissionUrl: "https://www.fastclaim.com/xfinitymobile",
    cmsPath: "https://xmagent.xmobiletest.com/cms/",
    cmsUrl: "https://retail.xmobiletest.com/cms/",
    cmsVersion: "master",
    confirmOrderHitTimes: 18,
    coverageMapUrl: "https://einstein360.cable.comcast.com/einstein360/ViewDocument/HOW11874",
    deactiveDeviceHitTimes: 3,
    dispoAPI: "https://emc-ms-commops-disposition-dev.g1.app.cloud.comcast.net/",
    doCustomerLookup: true,
    einstein360Url: "https://mcsweb-wc-uat-b.cable.comcast.com/einstein360",
    enableApiCache: true,
    enableCareBYOD: false,
    enableDisposition: true,
    enableDppToDppExchange: false,
    enableErrorLager: false,
    enableErrorLogger: true,
    enableExchanges: true,
    enableICCID: false,
    enableRetryPayments: true,
    enableRolePermission: true,
    enableRssx: true,
    enableSesitiveDataReplacement: true,
    enableShowSessionIdMenu: true,
    enableWA19: true,
    enableXMPP: true,
    env: "ci",
    exchangePreview: false,
    fedexTrackingUrl: "https://www.fedex.com/apps/fedextrack/?action=track&trackingnumber=",
    frequentlyAskedQuestions: "https://www.xfinity.com/mobile/support/article/115001835006/what-are-the-details-of-the-xfinity-mobile-protection-plan",
    gatewayUrl: "https://mbo-agentgateway-2-ci.codebig2.net/",
    hitOrderInterval: 10000,
    isMaintenanceMode: false,
    maintenanceEndTime: "July 27 2018 10:50 EDT",
    maintenanceMessage: "Maintenance scheduled for July 26st from 10pm to 11pm EDT.",
    maintenanceMessageDays: "3",
    maintenanceOverridePassword: "MODESTO!!!",
    maintenanceStartTime: "July 27 2018 10:45 EDT",
    migrationAlerts: true,
    omniChannelReturnExchange: false,
    orderActiveStateDays: 14,
    pcatUrl: "https://pcat-ci.mobile.xfinity.com/",
    placeOrderHitTimes: 30,
    pocketGeekUrl: "https://xfinity.pocketgeek.com/",
    portingPlaybookUrl: "https://www.xfinity.com/mobile/support/article/228042927",
    postAgentInfo: true,
    qaGatewayUrl: "https://mbo-agentgateway-qa.codebig2.net/",
    refundLowerLimit: "1",
    removeExchangeOnNoDpp: true,
    replacePhoneflag: true,
    retail360Url: "https://retail360-ci-nextgen.g2.app.cloud.comcast.net/",
    returnActiveStateDays: 20,
    returnsEnabled: true,
    sandboxApiUrl: "http://162.150.59.154:4300/api/",
    sandboxMockable: "https://mbo-gateway.getsandbox.com/",
    savingsCalculatorUrl: "https://www.xfinity.com/mobile/plan#savings-calculator",
    servicePhoneNumber: "(866) 461-0805",
    shouldCheckfor360Tokens: false,
    shouldShowByod: true,
    sprintUnlock: "https://www.sprint.com/legal/unlocking_policy.html",
    ssn9flag: true,
    supportIds: ["DriversLicense", "Passport", "StateId"],
    supportedHerobannerIds: "['optimize.multi', 'account.order.delivered', 'account.activation.failure', 'account.payment.failure']",
    tMobileUnlock: "https://support.t-mobile.com/docs/DOC-1588",
    termsAndConditions: "https://www.xfinity.com/mobile/policies/xmpp-terms",
    test: "https://mbo-customergateway-prod.codebig2.net/",
    test3: "",
    tradeInUrl: "https://www.google.com/",
    unlimitedSavingsDataRange: "3584",
    unlimitedWarningDataRange: "3072",
    updatedCreditCheck: true,
    upgradeIOSUrl: "https://support.apple.com/en-us/HT204204",
    verizonUnlock: "http://www.verizon.com/about/consumer-safety/device-unlocking-policy",
    websecUrl: "https://websec-oic.cable.comcast.com/",
    xfinityStoreLocationsUrl: "https://www.xfinity.com/support/service-center-locations/",
    xfinitymobileUrl: "xfinitymobile.com"
};

